import pandas as pd
data = pd.read_csv('train.csv')
print("Ввывод первых 10 строк файла")
print(data.head(10))
print("Ввывод метода info()")
print(data.info())
print("Ввывод детальной статистики для числовых столбцов")
print(data.describe().T)
print("Ввывод на экран определенных столбцов")
print(data[['Name', 'Sex', 'Age']].head())
print("Вывод данных только о пассажирах первого класса")
print(data[data['Pclass']==1].head(10))
print("Минимальная стоимость билета:")
print(data['Fare'].min())
print("Минимальная стоимость билета для взрослого пассажира:")
print(data[data['Age'] >= 18]['Fare'].min())
print("Возраст самого старого пассажира, путешествовавшего по бесплатному билету:")
print(data[data['Fare']==0]['Age'].max())
print("Минимальная стоимость билетов для детей:")
print(data[data['Age']<18]['Fare'].min())
print("Минимальная стоимость билетов для взрослых:")
print(data[data['Age']>18]['Fare'].min())
print("Средняя стоимость билета в первом классе:")
print(data[data['Pclass']==1]['Fare'].mean())
эксперементы с группировками
print("Статистика выживших и погибших:")
print(data['Survived'].value_counts())
print("Статистика выживших и погибших среди мужчин:")
print(data[data['Sex']=='male']['Survived'].value_counts())
print("Статистика выживших и погибших среди женщин:")
print(data[data['Sex']=='female']['Survived'].value_counts())
print("Статистика выживших и погибших среди женщин и мужчин:")
 for sex in data['Sex'].unique():
     if sex == 'male':
         print('Данные о мужчинах')
     else:
         print('Данные о женщинах')
     print(data[data['Sex']==sex]['Survived'].value_counts())
     print()
 for sex in data['Sex'].unique():
     if sex == 'male':
         print('Данные о мужчинах')
     else:
         print('Данные о женщинах')
     for pclass in data['Pclass'].unique():
         print('Данные о пассажирах {} класса'.format(pclass))
         print(data[(data['Sex']==sex) & (data['Pclass']==pclass)]
     ['Survived'].value_counts())
         print()
 print("Средний возраст выживших и погибших:")
 print(data.groupby(by = 'Survived')['Age'].mean())
 print("Средний возраст выживших и погибших по трем классам:")
 print(data.groupby(by = ['Survived', 'Pclass'])['Age'].mean())
 print("Количество выживших и погибших в зависимости от класса и пола:")
 print(data.groupby(by = ['Survived', 'Pclass', 'Sex'])['Fare'].count())
 print("Минимальная, средняя и максимальная стоимость билетов по классам")
 print(data.groupby(by='Pclass')['Fare'].agg([min, 'mean', max]))
 print("Минимальная, средня и максимальная стоимость билета для пассажиров в зависимости от пола и класса")
 print(data.groupby(by = ['Sex', 'Pclass'])['Fare'].agg([min, 'mean', max]))
 print("Средний возраст выживших и погибших пассажиров по классам")
 df.pivot_table(values = 'Age', index = 'Survived', columns = 'Pclass',aggfunc = 'mean')
 print("Минимальная, максимальная и средняя стоимость билета для выживших и погибших пассажиров в зависимости от пола и класса")
 print(df.pivot_table(values='Fare', index=['Survived', 'Sex'],columns='Pclass', aggfunc=(max,'mean', min)))
Извлекаем из полученных данных информацию для конкретной категории пассажиров
 print("Помещаем в отдельный датафрейм сгруппированные данные")
 data2 = data.pivot_table(values='Fare', index=['Survived', 'Sex'],columns='Pclass', aggfunc=(max,'mean', min))
 print("Средняя стоимость билета для погибших мужчин - пассажиров 1 класса:")
 data2['mean'][1][0]['male']
 print("Среднее количесто братьев, сестер и супругов ('SibSp'),которые путешествовали с выжившими и погибшими пассажирами разных классов")
 print(data.pivot_table(values = 'SibSp', index = 'Survived', columns ='Pclass', aggfunc = 'mean'))